add serde feature
insha/salah pull request #15
Opened 2024-12-28 10:22 UTC by ahmed80dz

to streamline serialisation and deserialition

2025-03-23 12:19 UTC, insha commented on .github/workflows/rust2.yml
Thank you for submitting this pull request 🙌 . 

When you have a moment, could you remove this file. A workflow file already exists in the repository and this file seems to be duplicate of it.

2025-03-23 12:27 UTC, insha requested changes
This is look good. Thank you! Please take a look at the single comment. Thanks again for your contribution 🙌.

2026-07-26 05:59 UTC, n4zguu1 commented
whats happening to this PR? @ahmed80dz

2026-08-05 18:57 UTC, insha commented
@n4zguu1 I am cleaning up this pull request and will be merging shortly. The changes will be part of an upcoming update.

2026-08-05 19:23 UTC, insha commented
Closing this pull request. It has been manually merged to the `main` branch.

2026-08-05 19:23 UTC, closed without merging